[RbControls]
TRbStyleManagerNTag=0
TRbControlColorsNDefaultFrom=14671839
TRbControlColorsNDefaultTo=16645629
TRbControlColorsNOverFrom=16777215
TRbControlColorsNOverTo=16777215
TRbControlColorsNClickedFrom=13158600
TRbControlColorsNClickedTo=16777215
TRbControlColorsNHotTrack=13500416
TRbControlColorsNBorderColor=5329233
TRbControlColorsNTextShadow=16777215
TRbStyleManagerEShowFocusRect=False
TRbStyleManagerEHotTrack=True
TRbStyleManagerEGradientBorder=True
TRbStyleManagerETextShadow=True
TRbStyleManagerNCheckColor=10310997
TRbStyleManagerEFadeSpeed=fsMedium
TRbStyleManagerNInnerColor=14933983
TRbStyleManagerNBorderColor=8421504
TRbSplitterColorsNDefaultFrom=-2147483633
TRbSplitterColorsNDefaultTo=-2147483633
TRbSplitterColorsNOverFrom=16777215
TRbSplitterColorsNOverTo=13158600
TRbStyleManagerNFontColor=-2147483640
TFontNCharset=1
TFontNColor=-2147483640
TFontNHeight=-11
TFontEPitch=fpDefault
TFontNSize=8
TFontSStyle=
TRbStyleManagerNPanelColor=14868704
