[RbControls]
TRbStyleManagerNTag=0
TRbControlColorsNDefaultFrom=16777215
TRbControlColorsNDefaultTo=13745839
TRbControlColorsNOverFrom=16777215
TRbControlColorsNOverTo=12489846
TRbControlColorsNClickedFrom=13029334
TRbControlColorsNClickedTo=15463415
TRbControlColorsNHotTrack=16711680
TRbControlColorsNBorderColor=8421504
TRbControlColorsNTextShadow=16777215
TRbStyleManagerEShowFocusRect=True
TRbStyleManagerEHotTrack=False
TRbStyleManagerEGradientBorder=True
TRbStyleManagerETextShadow=True
TRbStyleManagerNCheckColor=32768
TRbStyleManagerEFadeSpeed=fsMedium
TRbStyleManagerNInnerColor=14933983
TRbStyleManagerNBorderColor=8421504
TRbSplitterColorsNDefaultFrom=-2147483633
TRbSplitterColorsNDefaultTo=-2147483633
TRbSplitterColorsNOverFrom=16777215
TRbSplitterColorsNOverTo=12489846
TRbStyleManagerNFontColor=-2147483640
TFontNCharset=1
TFontNColor=-2147483640
TFontNHeight=-11
TFontEPitch=fpDefault
TFontNSize=8
TFontSStyle=
TRbStyleManagerNPanelColor=14933983
