[RbControls]
TRbControlColorsNDefaultFrom=6998271
TRbControlColorsNDefaultTo=1878783
TRbControlColorsNOverFrom=1747455
TRbControlColorsNOverTo=35033
TRbControlColorsNClickedFrom=11461119
TRbControlColorsNClickedTo=4635391
TRbControlColorsNHotTrack=3091825
TRbControlColorsNBorderColor=2763306
TRbControlColorsNTextShadow=9818879
TRbStyleManagerEShowFocusRect=False
TRbStyleManagerEHotTrack=False
TRbStyleManagerEGradientBorder=True
TRbStyleManagerNCheckColor=18805
TRbStyleManagerEFadeSpeed=fsFast
TRbStyleManagerNInnerColor=15398911
TRbStyleManagerNBorderColor=8421504
TRbSplitterColorsNDefaultFrom=-2147483633
TRbSplitterColorsNDefaultTo=-2147483633
TRbSplitterColorsNOverFrom=16777215
TRbSplitterColorsNOverTo=11461119
TRbStyleManagerNFontColor=0
TFontNCharset=1
TFontNColor=-2147483640
TFontNHeight=-11
TFontEPitch=fpDefault
TFontNSize=8
TFontSStyle=
TRbStyleManagerETextShadow=False
TRbStyleManagerNPanelColor=14938356
