[RbControls]
TRbControlColorsNDefaultFrom=15919850
TRbControlColorsNDefaultTo=14867160
TRbControlColorsNOverFrom=14340303
TRbControlColorsNOverTo=16777215
TRbControlColorsNClickedFrom=14465208
TRbControlColorsNClickedTo=16777215
TRbControlColorsNHotTrack=13500416
TRbControlColorsNBorderColor=5329233
TRbControlColorsNTextShadow=14408667
TRbStyleManagerEShowFocusRect=False
TRbStyleManagerEHotTrack=False
TRbStyleManagerEGradientBorder=False
TRbStyleManagerNCheckColor=10310997
TRbStyleManagerEFadeSpeed=fsFast
TRbStyleManagerNInnerColor=15130591
TRbStyleManagerNBorderColor=3487029
TRbSplitterColorsNDefaultFrom=-2147483633
TRbSplitterColorsNDefaultTo=-2147483633
TRbSplitterColorsNOverFrom=16777215
TRbSplitterColorsNOverTo=15130591
TRbStyleManagerNFontColor=4730157
TFontNCharset=0
TFontNColor=-2147483640
TFontNHeight=-11
TFontEPitch=fpDefault
TFontNSize=8
TFontSStyle=
TRbStyleManagerETextShadow=True
TRbStyleManagerNPanelColor=15723497
