[RbControls]
TRbControlColorsNDefaultFrom=13496297
TRbControlColorsNDefaultTo=9421491
TRbControlColorsNOverFrom=9421491
TRbControlColorsNOverTo=8234630
TRbControlColorsNClickedFrom=8371967
TRbControlColorsNClickedTo=13496297
TRbControlColorsNHotTrack=2636844
TRbControlColorsNBorderColor=5800032
TRbControlColorsNTextShadow=12709092
TRbStyleManagerEShowFocusRect=False
TRbStyleManagerEHotTrack=True
TRbStyleManagerEGradientBorder=True
TRbStyleManagerNCheckColor=5800032
TRbStyleManagerEFadeSpeed=fsMedium
TRbStyleManagerNInnerColor=14541279
TRbStyleManagerNBorderColor=5800032
TRbSplitterColorsNDefaultFrom=-2147483633
TRbSplitterColorsNDefaultTo=-2147483633
TRbSplitterColorsNOverFrom=13496297
TRbSplitterColorsNOverTo=8234630
TRbStyleManagerNFontColor=-2147483640
TFontNCharset=0
TFontNColor=-2147483640
TFontNHeight=-11
TFontEPitch=fpDefault
TFontNSize=8
TFontSStyle=fsBold
TRbStyleManagerETextShadow=True
TRbStyleManagerNPanelColor=14936291
