[RbControls]
TRbControlColorsNDefaultFrom=15592425
TRbControlColorsNDefaultTo=14999514
TRbControlColorsNOverFrom=1830398
TRbControlColorsNOverTo=35033
TRbControlColorsNClickedFrom=2403839
TRbControlColorsNClickedTo=8582655
TRbControlColorsNHotTrack=3091825
TRbControlColorsNBorderColor=2763306
TRbControlColorsNTextShadow=16777215
TRbStyleManagerEShowFocusRect=False
TRbStyleManagerEHotTrack=False
TRbStyleManagerEGradientBorder=True
TRbStyleManagerETextShadow=True
TRbStyleManagerNCheckColor=29623
TRbStyleManagerEFadeSpeed=fsFast
TRbStyleManagerNPanelColor=16118769
TRbStyleManagerNBorderColor=8421504
TRbSplitterColorsNDefaultFrom=-2147483633
TRbSplitterColorsNDefaultTo=-2147483633
TRbSplitterColorsNOverFrom=2403839
TRbSplitterColorsNOverTo=8582655
TFontNCharset=1
TFontNColor=-2147483640
TFontNHeight=-11
TFontEPitch=fpDefault
TFontNSize=8
TFontSStyle=
