[RbControls]
TRbControlColorsNDefaultFrom=16777215
TRbControlColorsNDefaultTo=16777215
TRbControlColorsNOverFrom=8816056
TRbControlColorsNOverTo=16777215
TRbControlColorsNClickedFrom=16777215
TRbControlColorsNClickedTo=8816056
TRbControlColorsNHotTrack=3091825
TRbControlColorsNBorderColor=8421504
TRbControlColorsNTextShadow=16579836
TRbStyleManagerEShowFocusRect=False
TRbStyleManagerEHotTrack=False
TRbStyleManagerEGradientBorder=True
TRbStyleManagerNCheckColor=3091825
TRbStyleManagerEFadeSpeed=fsFast
TRbStyleManagerNInnerColor=15198193
TRbStyleManagerNBorderColor=8421504
TRbSplitterColorsNDefaultFrom=-2147483633
TRbSplitterColorsNDefaultTo=-2147483633
TRbSplitterColorsNOverFrom=16777215
TRbSplitterColorsNOverTo=8816056
TRbStyleManagerNFontColor=3092043
TFontNCharset=0
TFontNColor=-2147483640
TFontNHeight=-11
TFontEPitch=fpDefault
TFontNSize=8
TFontSStyle=
TRbStyleManagerETextShadow=False
TRbStyleManagerNPanelColor=14870249
