[RbControls]
TRbControlColorsNDefaultFrom=16777215
TRbControlColorsNDefaultTo=15199215
TRbControlColorsNOverFrom=16777215
TRbControlColorsNOverTo=13029079
TRbControlColorsNClickedFrom=1159421
TRbControlColorsNClickedTo=16777215
TRbControlColorsNHotTrack=13500416
TRbControlColorsNBorderColor=7550976
TRbControlColorsNTextShadow=16777215
TRbStyleManagerEShowFocusRect=False
TRbStyleManagerEHotTrack=True
TRbStyleManagerEGradientBorder=True
TRbStyleManagerETextShadow=False
TRbStyleManagerNCheckColor=2855225
TRbStyleManagerEFadeSpeed=fsFast
TRbStyleManagerNPanelColor=14215660
TRbStyleManagerNBorderColor=7550976
TRbSplitterColorsNDefaultFrom=14215660
TRbSplitterColorsNDefaultTo=14215660
TRbSplitterColorsNOverFrom=16777215
TRbSplitterColorsNOverTo=14215660
TFontNCharset=1
TFontNColor=-2147483640
TFontNHeight=-11
TFontEPitch=fpDefault
TFontNSize=8
TFontSStyle=
